/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmerIndexRouteImport } from './routes/farmer/index'
import { Route as BuyerIndexRouteImport } from './routes/buyer/index'
import { Route as FarmerDashboardIndexRouteImport } from './routes/farmer/dashboard/index'
import { Route as BuyerDashboardIndexRouteImport } from './routes/buyer/dashboard/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/farmer/',
  path: '/farmer/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerIndexRoute = BuyerIndexRouteImport.update({
  id: '/buyer/',
  path: '/buyer/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerDashboardIndexRoute = FarmerDashboardIndexRouteImport.update({
  id: '/farmer/dashboard/',
  path: '/farmer/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerDashboardIndexRoute = BuyerDashboardIndexRouteImport.update({
  id: '/buyer/dashboard/',
  path: '/buyer/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/buyer/dashboard/': typeof BuyerDashboardIndexRoute
  '/farmer/dashboard/': typeof FarmerDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buyer': typeof BuyerIndexRoute
  '/farmer': typeof FarmerIndexRoute
  '/buyer/dashboard': typeof BuyerDashboardIndexRoute
  '/farmer/dashboard': typeof FarmerDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/buyer/dashboard/': typeof BuyerDashboardIndexRoute
  '/farmer/dashboard/': typeof FarmerDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buyer/'
    | '/farmer/'
    | '/buyer/dashboard/'
    | '/farmer/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/buyer' | '/farmer' | '/buyer/dashboard' | '/farmer/dashboard'
  id:
    | '__root__'
    | '/'
    | '/buyer/'
    | '/farmer/'
    | '/buyer/dashboard/'
    | '/farmer/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyerIndexRoute: typeof BuyerIndexRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
  BuyerDashboardIndexRoute: typeof BuyerDashboardIndexRoute
  FarmerDashboardIndexRoute: typeof FarmerDashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/farmer'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/': {
      id: '/buyer/'
      path: '/buyer'
      fullPath: '/buyer/'
      preLoaderRoute: typeof BuyerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/dashboard/': {
      id: '/farmer/dashboard/'
      path: '/farmer/dashboard'
      fullPath: '/farmer/dashboard/'
      preLoaderRoute: typeof FarmerDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/dashboard/': {
      id: '/buyer/dashboard/'
      path: '/buyer/dashboard'
      fullPath: '/buyer/dashboard/'
      preLoaderRoute: typeof BuyerDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyerIndexRoute: BuyerIndexRoute,
  FarmerIndexRoute: FarmerIndexRoute,
  BuyerDashboardIndexRoute: BuyerDashboardIndexRoute,
  FarmerDashboardIndexRoute: FarmerDashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
