/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmerIndexRouteImport } from './routes/farmer/index'
import { Route as FarmerPostStrawIndexRouteImport } from './routes/farmer/post-straw/index'
import { Route as FarmerDashboardIndexRouteImport } from './routes/farmer/dashboard/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/farmer/',
  path: '/farmer/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerPostStrawIndexRoute = FarmerPostStrawIndexRouteImport.update({
  id: '/farmer/post-straw/',
  path: '/farmer/post-straw/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerDashboardIndexRoute = FarmerDashboardIndexRouteImport.update({
  id: '/farmer/dashboard/',
  path: '/farmer/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/farmer/dashboard/': typeof FarmerDashboardIndexRoute
  '/farmer/post-straw/': typeof FarmerPostStrawIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/farmer': typeof FarmerIndexRoute
  '/farmer/dashboard': typeof FarmerDashboardIndexRoute
  '/farmer/post-straw': typeof FarmerPostStrawIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/farmer/dashboard/': typeof FarmerDashboardIndexRoute
  '/farmer/post-straw/': typeof FarmerPostStrawIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/farmer/' | '/farmer/dashboard/' | '/farmer/post-straw/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/farmer' | '/farmer/dashboard' | '/farmer/post-straw'
  id:
    | '__root__'
    | '/'
    | '/farmer/'
    | '/farmer/dashboard/'
    | '/farmer/post-straw/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
  FarmerDashboardIndexRoute: typeof FarmerDashboardIndexRoute
  FarmerPostStrawIndexRoute: typeof FarmerPostStrawIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/farmer'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/post-straw/': {
      id: '/farmer/post-straw/'
      path: '/farmer/post-straw'
      fullPath: '/farmer/post-straw/'
      preLoaderRoute: typeof FarmerPostStrawIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/dashboard/': {
      id: '/farmer/dashboard/'
      path: '/farmer/dashboard'
      fullPath: '/farmer/dashboard/'
      preLoaderRoute: typeof FarmerDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FarmerIndexRoute: FarmerIndexRoute,
  FarmerDashboardIndexRoute: FarmerDashboardIndexRoute,
  FarmerPostStrawIndexRoute: FarmerPostStrawIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
